### ISSUE TITLE
`index.html` links result in content-less pages

### ISSUE THREAD

**Issue by andy-faunadb** [faunadb/faunadb-ruby#120]
* Run `bundle exec rake rdoc`.
* Visit `doc/index.html`.
* Click on `#add` to go to `doc/Fauna/Query.html#method-i-add`.
* The page will just consist of headers: "Basic forms", "public instance methods", "Collections", "public instance methods", "Miscellaneous functions", "public instance methods", etc.

**Comment by ashfire908** [comment]
Unable to reproduce. Sounds like it was just rdoc bugging out.
