### ISSUE TITLE
query exceptions do not return position

### ISSUE THREAD

**Issue by freels** [faunadb/faunadb-ruby#153]
It's not included in the exception message, so it's inconvenient to get to when a raised exception is printed out.

**Comment by freels** [comment]
Ideally all validation errors would be printed out, perhaps. maybe just the first one?

**Comment by ashfire908** [comment]
What do we want the message to look like?

**Comment by freels** [comment]
Try playing with some queries that fail to get a handle on what raised exceptions look like. It should be possible to have an idea of why and where a query is failing w/o having to programmatically inspect the exception.

**Comment by ashfire908** [comment]
Some example output from the formatting I'm working on:

```
Fauna::BadRequest: Error at []: validation failed - Instance data is not valid. (Failure at [:name]: invalid type - Invalid type Long, expected type Name.)
Fauna::BadRequest: Error at [:get]: invalid argument - Identifier expected, String provided.
Fauna::BadRequest: Error at [0, :get]: invalid expression - Invalid ref. Error at [1, :get]: invalid expression - Invalid ref.
Fauna::NotFound: Error: not found - Not Found
Fauna::InternalError: Error: internal server error - Sample error
```

**Comment by freels** [comment]
Not found should have a path, too right?

**Comment by ashfire908** [comment]
Right now I'm not changing handling based on exception or core. What codes/exceptions should we display the path for?

**Comment by freels** [comment]
If it comes back from fauna with one it should be displayed.
