### ISSUE TITLE
Namespace for errors is confusing

### ISSUE THREAD

**Issue by freels** [faunadb/faunadb-ruby#51]
Fauna::Connection::NotFound makes it seem like it's a connection issue, rather than a 404 response.

Fauna::NotFound or Fauna::Resource::NotFound would be better.

**Comment by ashfire908** [comment]
Errors in the new client are now under the `Fauna` module directly, eg `Fauna::NotFound`. I believe that makes this solved?

**Comment by freels** [comment]
Yep
