### ISSUE TITLE
Rake task 'fauna:dump' broken

### ISSUE THREAD

**Issue by thebicycle2** [faunadb/faunadb-ruby#64]
The first issue is in line 37 of 'fauna.rake'
```
class_name = ref[0..-8]
```
If you have a class ref like "classes/thisisatest", the the class_name will be "classes/this". Ought to be
```
class_name = [8..-1]
```
If the ref is long enough, when `Dir.chdir(class_name)` is called on line 40, an additional 'classes' directory also is created.

Also, the `Fauna.connection.get(class_name)` on line 43 ought to be changed to `Fauna.connection.get(ref)`.

**Comment by ashfire908** [comment]
We are currently in the progress of rewriting the ruby client. Part of that is we are going to be dropping the rake tasks, as what they do is no longer supported.
