### ISSUE TITLE
Importing module methods should be possible

### ISSUE THREAD

**Issue by sprsquish** [faunadb/faunadb-ruby#91]
It should be easy to bring Query methods into scope in order to eliminate the need to namespace them.

For instance, I'd like to be able to do this:
```ruby
class Foo
  include Fauna::Query
  def createDB(dbName)
    create(Ref.new('databases'), quote(name: dbName))
  end
end
```

That's not possible without some hackery because the query methods are all module methods.

**Comment by andy-faunadb** [comment]
Fixed as of #110.
